// Generate the board-gated udev rules for ctt-radio-driver from the board radio
// maps in system/radios/maps/*.json. Run whenever a map changes; commit the output.
//
//   node system/radios/generate-rules.mjs
//
// Emits TWO static files, each containing every board's rules gated on
// ENV{CTT_BOARD} (imported from /run/ctt/board.env, which ctt-board-detect writes
// each boot — so a single static install self-selects the right board, survives a
// compute-module swap, and has nothing to clean up; non-matching blocks never fire):
//
//   system/udev/78-ctt-radio-driver.rules  — 434 MHz radios (Adafruit Feather 239a)
//   system/udev/78-ctt-blu-driver.rules     — BluSeries receivers (FTDI 0403:6015)
//
// Both classes share ONE source of truth: the maps/*.json port topology. A map
// entry { channel, id_path } is the physical USB position. The 434 radio gets that
// channel number directly. BluSeries receivers are external and plug into the
// off-board ports the radio map numbers 6+; for plug-n-play human readability we
// renumber those to start at 1 (blu ch = radio ch - BLU_CHANNEL_OFFSET). So a Blu
// in the port the radio map calls ch8 enumerates as blu ch3.
//
// On hotplug at a mapped position, udev symlinks /dev/ctt-{radio,blu}/ch<N> and
// starts ctt-{radio,blu}-driver@ch<N>, which serves /run/ctt/{radios,blu}/ch<N>.sock.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { dirname, join, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const MAPS_DIR = join(__dirname, 'maps')
const RADIO_OUT = join(__dirname, '..', 'udev', '78-ctt-radio-driver.rules')
const BLU_OUT = join(__dirname, '..', 'udev', '78-ctt-blu-driver.rules')

const LABELS = { v2: 'V2', v3r0: 'V3 rev 0/1', v3r3: 'V3 rev 2+' }

const RADIO_MATCH = 'ACTION=="add", SUBSYSTEM=="tty", ATTRS{idVendor}=="239a"'
const BLU_MATCH = 'ACTION=="add", SUBSYSTEM=="tty", ATTRS{idVendor}=="0403"'

// The radio app firmware enumerates as an Adafruit Feather 32u4 (idProduct 800c).
// Gate the per-channel rules on that, so the Caterina bootloader (idProduct 000c,
// which appears during programming) does NOT get a /dev/ctt-radio symlink or
// relaunch the driver — leaving the port free for ctt-radio-flash / avrdude.
const RADIO_APP_PID = '800c'

// BluSeries receivers present as an FTDI FT231X USB-UART (single product id; no
// bootloader/app split like the Feather).
const BLU_PID = '6015'

// Radio channels 1..5 are on-board (soldered) radios; 6+ are the external ports.
// Blu receivers reuse those external ports, renumbered to start at 1. Map the
// first BLU_MAX of them (blu ch = radio ch - BLU_CHANNEL_OFFSET).
const BLU_CHANNEL_OFFSET = 5
const BLU_MAX = 6

// The JSON filename (v2 / v3r0 / v3r3) IS the CTT_BOARD value.
function radioRule(board, { channel, id_path }) {
  return (
    `${RADIO_MATCH}, ATTRS{idProduct}=="${RADIO_APP_PID}", ENV{CTT_BOARD}=="${board}", ` +
    `ENV{ID_PATH}=="${id_path}", ENV{CTT_RADIO_CHANNEL}="${channel}", ` +
    `SYMLINK+="ctt-radio/ch${channel}", TAG+="systemd", ` +
    `ENV{SYSTEMD_WANTS}+="ctt-radio-driver@ch${channel}.service"`
  )
}

function bluRule(board, { channel, id_path }) {
  const blu = channel - BLU_CHANNEL_OFFSET
  return (
    `${BLU_MATCH}, ATTRS{idProduct}=="${BLU_PID}", ENV{CTT_BOARD}=="${board}", ` +
    `ENV{ID_PATH}=="${id_path}", ENV{CTT_BLU_CHANNEL}="${blu}", ` +
    `SYMLINK+="ctt-blu/ch${blu}", TAG+="systemd", ` +
    `ENV{SYSTEMD_WANTS}+="ctt-blu-driver@ch${blu}.service"`
  )
}

const boards = readdirSync(MAPS_DIR).filter((f) => f.endsWith('.json')).sort()

const radioLines = [
  `# GENERATED by system/radios/generate-rules.mjs - DO NOT EDIT.`,
  `# Board-gated 434 MHz radio rules. CTT_BOARD is imported from /run/ctt/board.env,`,
  `# which ctt-board-detect writes each boot (so a compute-module swap is handled).`,
  `# Single static install: only the matching board's block fires; nothing to clean up.`,
  ``,
  `# Resolve the board for radio devices.`,
  `${RADIO_MATCH}, IMPORT{file}="/run/ctt/board.env"`,
  ``,
]
const bluLines = [
  `# GENERATED by system/radios/generate-rules.mjs - DO NOT EDIT.`,
  `# Board-gated BluSeries receiver rules (FTDI ${'0403'}:${BLU_PID}). Same source of`,
  `# truth as the radios (system/radios/maps/) — Blu reuses the external ports the`,
  `# radio map numbers ${BLU_CHANNEL_OFFSET + 1}+, renumbered to start at 1 (blu ch = radio ch - ${BLU_CHANNEL_OFFSET}).`,
  `# CTT_BOARD comes from /run/ctt/board.env; only the matching board's block fires.`,
  ``,
  `# Resolve the board for Blu devices.`,
  `${BLU_MATCH}, IMPORT{file}="/run/ctt/board.env"`,
  ``,
]

let radioTotal = 0
let bluTotal = 0
for (const file of boards) {
  const board = basename(file, '.json')
  const map = JSON.parse(readFileSync(join(MAPS_DIR, file), 'utf8'))
  const label = LABELS[board] ?? board

  radioLines.push(`# --- ${label} ---`)
  for (const entry of map) radioLines.push(radioRule(board, entry))
  radioLines.push('')
  radioTotal += map.length

  const bluEntries = map.filter(
    (e) => e.channel > BLU_CHANNEL_OFFSET && e.channel <= BLU_CHANNEL_OFFSET + BLU_MAX
  )
  bluLines.push(`# --- ${label} ---`)
  for (const entry of bluEntries) bluLines.push(bluRule(board, entry))
  bluLines.push('')
  bluTotal += bluEntries.length
}

writeFileSync(RADIO_OUT, radioLines.join('\n'))
console.log(`wrote ${RADIO_OUT} (${boards.length} boards, ${radioTotal} channels)`)
writeFileSync(BLU_OUT, bluLines.join('\n'))
console.log(`wrote ${BLU_OUT} (${boards.length} boards, ${bluTotal} channels)`)
