// Generate the board-gated udev rules for ctt-radio-driver from the board radio
// maps in system/radios/maps/*.json. Run whenever a map changes; commit the output.
//
//   node system/radios/generate-rules.mjs
//
// Emits ONE static file (system/udev/78-ctt-radio-driver.rules) containing every
// board's rules, each block gated on ENV{CTT_BOARD}. CTT_BOARD is imported from
// /run/ctt/board.env, which ctt-station-id writes each boot — so a single static
// install self-selects the right board, survives a compute-module swap, and has
// nothing to clean up (the non-matching boards' blocks just never fire).
//
// Each map entry { channel, id_path }: on hotplug of the Adafruit Feather (239a)
// at that USB position, udev symlinks /dev/ctt-radio/ch<N> and starts
// ctt-radio-driver@ch<N>, which serves /run/ctt/radios/ch<N>.sock.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { dirname, join, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const MAPS_DIR = join(__dirname, 'maps')
const OUT = join(__dirname, '..', 'udev', '78-ctt-radio-driver.rules')

const LABELS = { v2: 'V2', v3r0: 'V3 rev 0/1', v3r3: 'V3 rev 2+' }
const MATCH = 'ACTION=="add", SUBSYSTEM=="tty", ATTRS{idVendor}=="239a"'

// The JSON filename (v2 / v3r0 / v3r3) IS the CTT_BOARD value.
function rule(board, { channel, id_path }) {
  return (
    `${MATCH}, ENV{CTT_BOARD}=="${board}", ENV{ID_PATH}=="${id_path}", ` +
    `ENV{CTT_RADIO_CHANNEL}="${channel}", SYMLINK+="ctt-radio/ch${channel}", ` +
    `TAG+="systemd", ENV{SYSTEMD_WANTS}+="ctt-radio-driver@ch${channel}.service"`
  )
}

const boards = readdirSync(MAPS_DIR).filter((f) => f.endsWith('.json')).sort()
const lines = [
  `# GENERATED by system/radios/generate-rules.mjs - DO NOT EDIT.`,
  `# Board-gated 434 MHz radio rules. CTT_BOARD is imported from /run/ctt/board.env,`,
  `# which ctt-station-id writes each boot (so a compute-module swap is handled).`,
  `# Single static install: only the matching board's block fires; nothing to clean up.`,
  ``,
  `# Resolve the board for radio devices.`,
  `${MATCH}, IMPORT{file}="/run/ctt/board.env"`,
  ``,
]
let total = 0
for (const file of boards) {
  const board = basename(file, '.json')
  const map = JSON.parse(readFileSync(join(MAPS_DIR, file), 'utf8'))
  lines.push(`# --- ${LABELS[board] ?? board} ---`)
  for (const entry of map) lines.push(rule(board, entry))
  lines.push('')
  total += map.length
}
writeFileSync(OUT, lines.join('\n'))
console.log(`wrote ${OUT} (${boards.length} boards, ${total} channels)`)
