export default {
  http: { websocket_port: 8001, flush_websocket_messages_seconds: 1 },
  blu_radios: {
    1: {
      name: "polling_interval",
      enabled: true,
      record: true,
      description: "duration",
      type: "integer",
      required: false,
      display_name: "Polling Interval",
      units: "ms",
      values: {
        min: 1000,
        max: 30000,
        default: 10000,
        current: 10000,
        warn_min: {
          value: 30000,
          description: "You may lose detections at this poll interval.",
        },
      },
    },
    2: {
      name: "polling_interval",
      enabled: true,
      record: true,
      description: "duration",
      type: "integer",
      required: false,
      display_name: "Polling Interval",
      units: "ms",
      values: {
        min: 1000,
        max: 30000,
        default: 10000,
        current: 10000,
        warn_min: {
          value: 30000,
          description: "You may lose detections at this poll interval.",
        },
      },
    },
    3: {
      name: "polling_interval",
      enabled: true,
      record: true,
      description: "duration",
      type: "integer",
      required: false,
      display_name: "Polling Interval",
      units: "ms",
      values: {
        min: 1000,
        max: 30000,
        default: 10000,
        current: 10000,
        warn_min: {
          value: 30000,
          description: "You may lose detections at this poll interval.",
        },
      },
    },
    4: {
      name: "polling_interval",
      enabled: true,
      record: true,
      description: "duration",
      type: "integer",
      required: false,
      display_name: "Polling Interval",
      units: "ms",
      values: {
        min: 1000,
        max: 30000,
        default: 10000,
        current: 10000,
        warn_min: {
          value: 30000,
          description: "You may lose detections at this poll interval.",
        },
      },
    },
  }
}